import { expect } from 'chai';

import { announceContestant } from './contestant.js';
import { announceBossWillSpawn } from './bossWillSpawn.js';
import { RING_PATRON, RING_PATRON_NAME } from '../constants/lore.js';

function capture() {
	const published: Array<{ text: string }> = [];
	return {
		eb: { publish: (event: { text: string }) => published.push(event) } as any,
		published,
	};
}

function makeContestant({ isBoss }: { isBoss: boolean }) {
	return {
		isBoss,
		character: { givenName: 'Incredible Swan', icon: '🎎', identity: '🎎 Incredible Swan' },
		monster: {
			icon: '🐗',
			givenName: 'Seeskane Orcbane',
			creatureType: 'Minotaur',
			individualDescription: 'A battle-hardened, gray minotaur.',
			stats: 'Type: Minotaur\nClass: Barbarian',
			rankings: 'Battles fought: 95\nBattles won: 65',
		},
	};
}

describe('announceContestant', () => {
	// The player and boss lines are a deliberate minimal pair: same shape, opposite
	// consent. A player's monster came willingly; a boss was commanded.
	it("says a player's monster answered a call, not that it was sent", () => {
		const { eb, published } = capture();
		announceContestant(eb, 'Ring', {}, { contestant: makeContestant({ isBoss: false }) });

		expect(published).to.have.lengthOf(1);
		expect(published[0]!.text).to.include('answers the call of 🎎 Incredible Swan.');
		expect(published[0]!.text).to.not.include('behest');
	});

	// A boss's owner is generated by `randomCharacter` under userId 'boss', so naming it
	// invented a beastmaster who does not exist — and for a timer-spawned boss it told
	// players someone had sent it in when nobody had. See 10b-bugs-fixed.md #102.
	it('credits the house for a boss, never the generated owner', () => {
		const { eb, published } = capture();
		announceContestant(eb, 'Ring', {}, { contestant: makeContestant({ isBoss: true }) });

		expect(published).to.have.lengthOf(1);
		// `Incredible Swan` is a randomly generated owner, not a player — naming it told
		// the room someone had sent the boss in when nobody had.
		expect(published[0]!.text).to.not.include('Incredible Swan');
		expect(published[0]!.text).to.include(`at the behest of ${RING_PATRON}.`);
	});

	it('is commanded rather than called, so the two lines cannot be confused', () => {
		const { eb, published } = capture();
		announceContestant(eb, 'Ring', {}, { contestant: makeContestant({ isBoss: true }) });

		expect(published[0]!.text).to.not.include('answers the call');
	});

	it('routes the house name through one constant, so it renames in one place', () => {
		const { eb, published } = capture();
		announceContestant(eb, 'Ring', {}, { contestant: makeContestant({ isBoss: true }) });

		expect(published[0]!.text).to.include(RING_PATRON_NAME);
	});

	it('still shows the boss stat card', () => {
		const { eb, published } = capture();
		announceContestant(eb, 'Ring', {}, { contestant: makeContestant({ isBoss: true }) });

		expect(published[0]!.text).to.include('Seeskane Orcbane');
	});
});

describe('announceBossWillSpawn', () => {
	// Every other line in the ring feed ends in a full stop; this one did not.
	it('ends the warning with a full stop', () => {
		const { eb, published } = capture();
		announceBossWillSpawn(eb, 'Ring', {}, { delay: 120_000 });

		expect(published).to.have.lengthOf(1);
		expect(published[0]!.text).to.match(/\.$/);
		expect(published[0]!.text).to.include('A boss will enter the ring');
	});
});
