/**
 * Naming for the house — the unseen authority that stages the games and decides what
 * comes through the gates.
 *
 * Bosses used to be credited to `character.givenName`, but a boss's owner is generated by
 * `randomCharacter` under `userId: 'boss'`, so every boss arrival named a beastmaster who
 * does not exist (10b-bugs-fixed.md #102). Naming the house instead of nobody keeps the
 * sense that something *sent* the boss, which is what the arrival line is for.
 *
 * "Editor" is the Roman term, not a pun: the *editor muneris* sponsored the games, set the
 * programme, and gave the signal. It is precisely the role being named here. The crown
 * disambiguates it from the `edit monster` / `edit character` commands.
 *
 * Kept as one constant so the house can be renamed in a single line — this is the game's
 * voice, and voice decisions get revisited.
 */
export const RING_PATRON_NAME = 'The Editor';
export const RING_PATRON_ICON = '👑';

/** Icon + name, as it appears inline in ring narration. */
export const RING_PATRON = `${RING_PATRON_ICON} ${RING_PATRON_NAME}`;
